language: node_js
node_js:
  - "6.3"
install:
  - npm install -g angular-cli
  - npm install  
script:
  #- npm test
  - npm run build:prod
after_success:
  # Deploy to firebase hosting
  - ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN
deploy:
  # Deploy to github pages
  - ng github-pages:deploy
  
sudo: false
